FROM node:24-slim AS frontend-build
WORKDIR /app
COPY frontend/package.json frontend/pnpm-lock.yaml ./
RUN corepack enable && pnpm install --frozen-lockfile
COPY frontend ./
RUN pnpm build

FROM caddy:2-alpine
COPY --from=frontend-build /app/dist /srv
COPY Caddyfile /etc/caddy/Caddyfile
